### ISSUE TITLE
Background issues

### ISSUE THREAD

**Issue by andreground** [Telerik-Verified-Plugins/AppleWatch#11] opened 2015-09-12 23:14 UTC
Hi,
Thanks for releasing this great plugin.

Everything works fine until the iOS app stays in foreground. Watch app and glance get updated with no issues.

If the app goes background or gets killed instead, then the watch will not be able to communicate anymore with the Cordova application.

Thus, for example, if you try to reboot the watch and then launch the watch app you will stay stuck with a black screen. To have it update, you'll have to manually launche the iOS application.

**Comment by EddyVerbruggen** [comment] 2015-09-13 05:53
That's unexpected behaviour - it should keep working as long as the Watch can communicate with the Phone (bluetooth on, paired). Are glances of other apps able to update during this time?

If you need assistance please share your project with me and I'd gladly take a look. Strip out anything unrelated to the problem if possible.

**Comment by andreground** [comment] 2015-09-13 07:14
Yes, all other apps and glances are working fine.

You can easily reproduce the bug following these steps:

1) start a blank ionic project (ionic start blank)
2) configure Xcode project and add your plugin
3) use your demo as index.html
4) run the application from Xcode
5) app will be installed correctly on phone and watch
6) run the app on the iPhone but NOT on the watch
7) put iPhone app in background a few seconds after it starts then run the app on the watch
8) watch screen will be black (bad)
9) resume app from background and watch screen will be immediately updated

Test #2:

1) put phone app in background
2) reboot watch
3) run app from watch
4) watch app will stay black until you resume phone app from background

The strange thing is that occasionally I can have it working in both situations even with phone app in background but most of the times it behaves as described in my two test case. I'll be happy to share my project in any case, if needed.

Please note that I'm running iOS 9 GM and watchOS1.

**Comment by EddyVerbruggen** [comment] 2015-09-13 07:24
Ah, iOS9 may be the issue then. I smoketested it, but perhaps not this case. Will do today, thx!

**Comment by EddyVerbruggen** [comment] 2015-09-13 07:53
Yep, reproduced it on iOS9. Hope to find a solution asap.

**Comment by EddyVerbruggen** [comment] 2015-09-13 10:04
Hi @andreground, I've pushed an update to master (0.6.0-dev), could you try that one please?

Make sure to remove `applewatch.registerNotifications..` from the demo index.html because it may interfere with this test a little. Will look at that once this has been tackled.

**Comment by andreground** [comment] 2015-09-13 10:32
Sure @EddyVerbruggen !

I'll make more deep testing but I can already give you one quick feedback: app seems now surviving background mode but still watch is black if app gets killed or phone is rebooted before starting the app on the watch.

Steps to reproduce:

1) run the application from Xcode
2) app will be installed correctly on phone and watch
3) run the app on the iPhone but NOT on the watch
4) kill iPhone app and run app from watch

You'll get black app and glance. Same if:

1) run the application from Xcode
2) app will be installed correctly on phone and watch
3) run the app on the iPhone but NOT on the watch
4) reboot iPhone and run app from watch

**Comment by EddyVerbruggen** [comment] 2015-09-13 10:37
If you swipe away from the glance and get back to it, do you then see it? The app needs a little time to spin up the first time after a reboot..

Thx for the quick feedback btw!

Checking a few things:
- We're both running Xcode 7 GM and iPhone 6 GM with WatchOS 1
- We're both starting the app with the WatchKit App target (I've also tested with the Phone App target)?

I just removed the app from both devices and followed your steps:
1) run the application from Xcode
2) app will be installed correctly on phone and watch
3) run the app on the iPhone but NOT on the watch
4) kill iPhone app and run app from watch

After a few moments of blank screen after 4) the UI appeared on the Watch.
**Make sure Xcode doesn't hang when you kill your app!**

Perhaps it's best to try a minimal index.html instead:

``` html
<!DOCTYPE html>
<html>
<head>
  <meta name="format-detection" content="telephone=no">
  <meta name="msapplication-tap-highlight" content="no">
  <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width">
  <link rel="stylesheet" type="text/css" href="css/index.css">
  <title>Hello World</title>
</head>
<body>
<div class="app">
  <h1>Apache Cordova</h1>

  <div id="deviceready" class="blink">
    <p class="event listening">Connecting to Device</p>

    <p class="event received">Device is Ready</p>
  </div>
</div>
<script type="text/javascript" src="cordova.js"></script>
<script type="text/javascript" src="js/index.js"></script>
<script>
  function onGlanceRequestsUpdate() {
    applewatch.loadGlance({
      'label2': {'value': 'Rendered at ' + new Date(), 'color': '#FFFFFF'}
    })
  }

  function onAppRequestsUpdate() {
    var payload = {
      'label2': { // optional, max 2 lines
        'value': 'UI built @ ' + new Date(),
        'color': '#FFFFFF',
        'font': {
          'size': 8 // default 12
        }
      }
    };
    applewatch.loadAppMain(payload);
  }

  function initAppleWatch() {
    applewatch.init(function () {
    });
    applewatch.callback.onLoadAppMainRequest = onAppRequestsUpdate;
    applewatch.callback.onLoadGlanceRequest = onGlanceRequestsUpdate;
  }

  document.addEventListener('deviceready', initAppleWatch, false);
</script>
</body>
</html>
```

**Comment by andreground** [comment] 2015-09-13 13:18
Nope, I see the loader spinning for a few seconds in the upper right of the glance screen but nothing gets pushed from the phone app. Is it the same for you?

**Comment by EddyVerbruggen** [comment] 2015-09-13 13:33
No, glances behave the same for me. How are you launching the app to test the glance, and are you gracefully stopping the debugger before killing the app on the phone?

**Comment by andreground** [comment] 2015-09-13 13:37
Actually no, I don't gracefully stop the debugger before killing the app...should I?
Concerning app launch, I always run the iPhone app from Xcode while starting the watch one directly by tapping on the watch.

**Comment by EddyVerbruggen** [comment] 2015-09-13 13:47
If you kill your app after just having it launch from Xcode, Xcode will 'hang' your app (in my experience). Try pressing 'stop' in Xcode before killing the app.

You can also start the watch app or glance directly from Xcode if you select their respective targets. That's at least what I do to quickly test my changes. It should even save you the trouble of having to kill the phone app.

Here's how I start a glance:
<img width="698" alt="screen shot 2015-09-13 at 15 50 29" src="https://cloud.githubusercontent.com/assets/1426370/9836978/cf951aa2-5a2e-11e5-9b5e-7830bf13fd53.png">

**Comment by andreground** [comment] 2015-09-13 14:09
Good point, I'll try to stop it from Xcode instead of killing it and let you know.

Have you had the same outcomes in both situations I reported a few comments ago?

**Comment by EddyVerbruggen** [comment] 2015-09-13 14:30
The behaviour here was ok (not with the 0.5.0 version though). Please also replace your index.html with the one I provided a few comments ago, just to rule out other errors. Thanks for your efforts, much appreciated!

**Comment by andreground** [comment] 2015-09-13 14:39
I do appreciate your support very much, thanks!

Btw, I did miss your comment with these two questions:

1)We're both running Xcode 7 GM and iPhone 6 GM with WatchOS 1 
Yes, Xcode 7 GM, iPhone 6 on iOS 9 GM with WatchOS 1

2) We're both starting the app with the WatchKit App target (I've also tested with the Phone App target)
No, I always used Phone as target in Xcode.

Given your outocomes, I'll strip my html down to the one you posted and make another complete round of tests.

My test paths will be:

![schermata 2015-09-13 alle 16 39 22](https://cloud.githubusercontent.com/assets/3788592/9837142/0616eee6-5a36-11e5-80aa-a312fd488984.png)

**Comment by andreground** [comment] 2015-09-14 08:10
First round of tests: 100% OK!!!
@EddyVerbruggen Thanks a billion for your effort and for the gold hint about ALWAYS stopping app from Xcode before any phone operation! :+1: 

![schermata 2015-09-14 alle 10 08 24](https://cloud.githubusercontent.com/assets/3788592/9845056/91e38352-5ac8-11e5-8a90-48123b320be6.png)

**Comment by EddyVerbruggen** [comment] 2015-09-14 10:13
Superawesome! Thanks for your thorough tests, you've helped making this plugin better compatible with iOS9 (and I sneaked in a few small fixes for WatchOS2 as well).

v0.6.0 has been released. :+1:

**Closed as completed by EddyVerbruggen** 2015-09-14 10:13 UTC
